/*
 * generated by Xtext 2.20.0
 */
package dk.sdu.mmmi


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SpringBoardRuntimeModule extends AbstractSpringBoardRuntimeModule {
}
