/*
 * generated by Xtext 2.20.0
 */
package dk.sdu.mmmi


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SpringBoardStandaloneSetup extends SpringBoardStandaloneSetupGenerated {

	def static void doSetup() {
		new SpringBoardStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
